version: "3"
services:
  web:
    build: .
    ports:
      - "3333:3333"
    image: "boilerplate${BUILD_NUMBER}"
    restart: always
    env_file:
      - ./.env.production
    environment:
      - NODE_ENV=production
    container_name: boilerplate
